services:
  redis:
    image: redis:8
    ports:
      - 6379:6379
    restart: always
  mongo:
    image: mongo:8
    ports:
      - ${MONGODB_PORT:-27017}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASS}
    restart: always
  express: 
    image: mongo-express:1.0.2
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${EXPRESS_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${EXPRESS_PASS}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASS}
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo
  producer:
    build: scheduler/producer
    environment:
      - BROKER_HOST=redis
    ports:
      - 5001:5000
    depends_on:
      - consumer
  consumer:
    build: scheduler/consumer
    environment:
      - BROKER_HOST=redis
    depends_on:
      - redis
  
